### ISSUE TITLE
Unable to delete plain text file

### ISSUE THREAD

**Issue by abelland** [fazo96/ipfs-drive#1]
`Uncaught (in promise) TypeError: Cannot read property 'size' of null` thrown

**Comment by fazo96** [comment]
Hi, I just published a new version on IPFS. You might want to try again if you are still interested :smile: https://ipfs.io/ipfs/QmSLoHumxHbaFLSk5tZCvJhhEwt5iNy7P5aPdmWWCjDdKx/
