### ISSUE TITLE
Endless loading screens

### ISSUE THREAD

**Issue by Falsen** [fazo96/ipfs-drive#3]
This project is very interesting indeed, but I am met with endless loading screens when adding files and doing other stuff. Am I doing anything wrong?

URL Used: https://ipfs.io/ipfs/QmSLoHumxHbaFLSk5tZCvJhhEwt5iNy7P5aPdmWWCjDdKx/#/ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn

**Comment by joelamouche** [comment]
Same here ! I would be interested in using this tool, but I just het a spinner when clicking on 'open empty folder'

**Comment by fazo96** [comment]
Hey guys, I think this is happening because the project is using a very outdated version of JS-IPFS.

I hope I get to update it soon, I'll close this when a new version is released.

**Comment by joelamouche** [comment]
@fazo96 I'm thinking about creating an open source decentralized database for music samples using IPFS, which is why I'm interested in seeing your project working, to use it or take inspiration from it

**Comment by fazo96** [comment]
I just updated the app to use the latest JS-IPFS release, the new version has been deployed to IPFS and the link is in the README.

Closing this, but feel free to comment and reopen if the problem happens again.
